version: '3.4'

networks: 
    demoapp:

services:
  demoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
    - 1433:1433
    volumes:
    - ./docker/sql/mssql/data:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Test1234= -i MovieDB_2.publish.sql || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234=
  cybersecu_movieapi:
    container_name: demo-blazor
    image: ${DOCKER_REGISTRY-}cybersecumovieapi
    build:
      context: .
      dockerfile: CyberSecu_MovieAPI/Dockerfile
    ports:
        - 8001:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=movieDb
      - DB_SA_PASSWORD=Test1234=
