CREATE TABLE [dbo].[Comments]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Content VARCHAR(MAX) NOT NULL,
	PostDate DATETIME2(7) NOT NULL,
	IdUser INT,
	IdMovie INT
	CONSTRAINT FK_User FOREIGN KEY (IdUser) REFERENCES Users(Id),
	CONSTRAINT FK_Movie FOREIGN KEY (IdMovie) REFERENCES Movie(Id),

)
